// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=./mock_domain/runner_mock.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/kavos113/seseragi/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNodeRunner is a mock of NodeRunner interface.
type MockNodeRunner struct {
	ctrl     *gomock.Controller
	recorder *MockNodeRunnerMockRecorder
	isgomock struct{}
}

// MockNodeRunnerMockRecorder is the mock recorder for MockNodeRunner.
type MockNodeRunnerMockRecorder struct {
	mock *MockNodeRunner
}

// NewMockNodeRunner creates a new mock instance.
func NewMockNodeRunner(ctrl *gomock.Controller) *MockNodeRunner {
	mock := &MockNodeRunner{ctrl: ctrl}
	mock.recorder = &MockNodeRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeRunner) EXPECT() *MockNodeRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockNodeRunner) Run(node domain.Node, task domain.Task, workflowRunID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", node, task, workflowRunID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockNodeRunnerMockRecorder) Run(node, task, workflowRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockNodeRunner)(nil).Run), node, task, workflowRunID)
}
