// Code generated by MockGen. DO NOT EDIT.
// Source: workflow.go
//
// Generated by this command:
//
//	mockgen -source=workflow.go -destination=./mock_domain/workflow_mock.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"
	time "time"

	domain "github.com/kavos113/seseragi/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowRepository is a mock of WorkflowRepository interface.
type MockWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkflowRepositoryMockRecorder is the mock recorder for MockWorkflowRepository.
type MockWorkflowRepositoryMockRecorder struct {
	mock *MockWorkflowRepository
}

// NewMockWorkflowRepository creates a new mock instance.
func NewMockWorkflowRepository(ctrl *gomock.Controller) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRepository) EXPECT() *MockWorkflowRepositoryMockRecorder {
	return m.recorder
}

// AddNodeToWorkflow mocks base method.
func (m *MockWorkflowRepository) AddNodeToWorkflow(workflowID string, node domain.Node) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNodeToWorkflow", workflowID, node)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNodeToWorkflow indicates an expected call of AddNodeToWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) AddNodeToWorkflow(workflowID, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNodeToWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).AddNodeToWorkflow), workflowID, node)
}

// CreateWorkflow mocks base method.
func (m *MockWorkflowRepository) CreateWorkflow(workflow domain.Workflow) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkflow", workflow)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkflow indicates an expected call of CreateWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) CreateWorkflow(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).CreateWorkflow), workflow)
}

// DeleteNodeFromWorkflow mocks base method.
func (m *MockWorkflowRepository) DeleteNodeFromWorkflow(workflowID, nodeName string) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeFromWorkflow", workflowID, nodeName)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNodeFromWorkflow indicates an expected call of DeleteNodeFromWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) DeleteNodeFromWorkflow(workflowID, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeFromWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).DeleteNodeFromWorkflow), workflowID, nodeName)
}

// DeleteWorkflow mocks base method.
func (m *MockWorkflowRepository) DeleteWorkflow(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkflow", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkflow indicates an expected call of DeleteWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) DeleteWorkflow(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).DeleteWorkflow), id)
}

// GetAllWorkflows mocks base method.
func (m *MockWorkflowRepository) GetAllWorkflows() ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWorkflows")
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWorkflows indicates an expected call of GetAllWorkflows.
func (mr *MockWorkflowRepositoryMockRecorder) GetAllWorkflows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWorkflows", reflect.TypeOf((*MockWorkflowRepository)(nil).GetAllWorkflows))
}

// GetWorkflowByID mocks base method.
func (m *MockWorkflowRepository) GetWorkflowByID(id string) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowByID", id)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowByID indicates an expected call of GetWorkflowByID.
func (mr *MockWorkflowRepositoryMockRecorder) GetWorkflowByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowByID", reflect.TypeOf((*MockWorkflowRepository)(nil).GetWorkflowByID), id)
}

// UpdateWorkflow mocks base method.
func (m *MockWorkflowRepository) UpdateWorkflow(workflow domain.Workflow) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkflow", workflow)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkflow indicates an expected call of UpdateWorkflow.
func (mr *MockWorkflowRepositoryMockRecorder) UpdateWorkflow(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkflow", reflect.TypeOf((*MockWorkflowRepository)(nil).UpdateWorkflow), workflow)
}

// MockWorkflowRunRepository is a mock of WorkflowRunRepository interface.
type MockWorkflowRunRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRunRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkflowRunRepositoryMockRecorder is the mock recorder for MockWorkflowRunRepository.
type MockWorkflowRunRepositoryMockRecorder struct {
	mock *MockWorkflowRunRepository
}

// NewMockWorkflowRunRepository creates a new mock instance.
func NewMockWorkflowRunRepository(ctrl *gomock.Controller) *MockWorkflowRunRepository {
	mock := &MockWorkflowRunRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowRunRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRunRepository) EXPECT() *MockWorkflowRunRepositoryMockRecorder {
	return m.recorder
}

// CreateWorkflowRun mocks base method.
func (m *MockWorkflowRunRepository) CreateWorkflowRun(workflowRun domain.WorkflowRun) (domain.WorkflowRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkflowRun", workflowRun)
	ret0, _ := ret[0].(domain.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkflowRun indicates an expected call of CreateWorkflowRun.
func (mr *MockWorkflowRunRepositoryMockRecorder) CreateWorkflowRun(workflowRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflowRun", reflect.TypeOf((*MockWorkflowRunRepository)(nil).CreateWorkflowRun), workflowRun)
}

// GetAllWorkflowRuns mocks base method.
func (m *MockWorkflowRunRepository) GetAllWorkflowRuns() ([]domain.WorkflowRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWorkflowRuns")
	ret0, _ := ret[0].([]domain.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWorkflowRuns indicates an expected call of GetAllWorkflowRuns.
func (mr *MockWorkflowRunRepositoryMockRecorder) GetAllWorkflowRuns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWorkflowRuns", reflect.TypeOf((*MockWorkflowRunRepository)(nil).GetAllWorkflowRuns))
}

// GetWorkflowRunByID mocks base method.
func (m *MockWorkflowRunRepository) GetWorkflowRunByID(id string) (domain.WorkflowRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowRunByID", id)
	ret0, _ := ret[0].(domain.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowRunByID indicates an expected call of GetWorkflowRunByID.
func (mr *MockWorkflowRunRepositoryMockRecorder) GetWorkflowRunByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowRunByID", reflect.TypeOf((*MockWorkflowRunRepository)(nil).GetWorkflowRunByID), id)
}

// GetWorkflowRunsAfter mocks base method.
func (m *MockWorkflowRunRepository) GetWorkflowRunsAfter(workflowID string, before time.Time) ([]domain.WorkflowRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowRunsAfter", workflowID, before)
	ret0, _ := ret[0].([]domain.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowRunsAfter indicates an expected call of GetWorkflowRunsAfter.
func (mr *MockWorkflowRunRepositoryMockRecorder) GetWorkflowRunsAfter(workflowID, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowRunsAfter", reflect.TypeOf((*MockWorkflowRunRepository)(nil).GetWorkflowRunsAfter), workflowID, before)
}

// GetWorkflowRunsByWorkflowID mocks base method.
func (m *MockWorkflowRunRepository) GetWorkflowRunsByWorkflowID(workflowID string) ([]domain.WorkflowRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowRunsByWorkflowID", workflowID)
	ret0, _ := ret[0].([]domain.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowRunsByWorkflowID indicates an expected call of GetWorkflowRunsByWorkflowID.
func (mr *MockWorkflowRunRepositoryMockRecorder) GetWorkflowRunsByWorkflowID(workflowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowRunsByWorkflowID", reflect.TypeOf((*MockWorkflowRunRepository)(nil).GetWorkflowRunsByWorkflowID), workflowID)
}
