// Code generated by MockGen. DO NOT EDIT.
// Source: workflow.go
//
// Generated by this command:
//
//	mockgen -source=workflow.go -destination=./mock_usecase/workflow_mock.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	domain "github.com/kavos113/seseragi/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowUseCase is a mock of WorkflowUseCase interface.
type MockWorkflowUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowUseCaseMockRecorder
	isgomock struct{}
}

// MockWorkflowUseCaseMockRecorder is the mock recorder for MockWorkflowUseCase.
type MockWorkflowUseCaseMockRecorder struct {
	mock *MockWorkflowUseCase
}

// NewMockWorkflowUseCase creates a new mock instance.
func NewMockWorkflowUseCase(ctrl *gomock.Controller) *MockWorkflowUseCase {
	mock := &MockWorkflowUseCase{ctrl: ctrl}
	mock.recorder = &MockWorkflowUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowUseCase) EXPECT() *MockWorkflowUseCaseMockRecorder {
	return m.recorder
}

// AddWorkflow mocks base method.
func (m *MockWorkflowUseCase) AddWorkflow(workflow domain.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkflow", workflow)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWorkflow indicates an expected call of AddWorkflow.
func (mr *MockWorkflowUseCaseMockRecorder) AddWorkflow(workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkflow", reflect.TypeOf((*MockWorkflowUseCase)(nil).AddWorkflow), workflow)
}

// DeleteWorkflow mocks base method.
func (m *MockWorkflowUseCase) DeleteWorkflow(workflowID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkflow", workflowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkflow indicates an expected call of DeleteWorkflow.
func (mr *MockWorkflowUseCaseMockRecorder) DeleteWorkflow(workflowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkflow", reflect.TypeOf((*MockWorkflowUseCase)(nil).DeleteWorkflow), workflowID)
}

// ListWorkflows mocks base method.
func (m *MockWorkflowUseCase) ListWorkflows() ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkflows")
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkflows indicates an expected call of ListWorkflows.
func (mr *MockWorkflowUseCaseMockRecorder) ListWorkflows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkflows", reflect.TypeOf((*MockWorkflowUseCase)(nil).ListWorkflows))
}
