// Code generated by MockGen. DO NOT EDIT.
// Source: workflow_run.go
//
// Generated by this command:
//
//	mockgen -source=workflow_run.go -destination=./mock_usecase/workflow_run_mock.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	domain "github.com/kavos113/seseragi/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowRunUseCase is a mock of WorkflowRunUseCase interface.
type MockWorkflowRunUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRunUseCaseMockRecorder
	isgomock struct{}
}

// MockWorkflowRunUseCaseMockRecorder is the mock recorder for MockWorkflowRunUseCase.
type MockWorkflowRunUseCaseMockRecorder struct {
	mock *MockWorkflowRunUseCase
}

// NewMockWorkflowRunUseCase creates a new mock instance.
func NewMockWorkflowRunUseCase(ctrl *gomock.Controller) *MockWorkflowRunUseCase {
	mock := &MockWorkflowRunUseCase{ctrl: ctrl}
	mock.recorder = &MockWorkflowRunUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRunUseCase) EXPECT() *MockWorkflowRunUseCaseMockRecorder {
	return m.recorder
}

// GetWorkflowsToRun mocks base method.
func (m *MockWorkflowRunUseCase) GetWorkflowsToRun() ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowsToRun")
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowsToRun indicates an expected call of GetWorkflowsToRun.
func (mr *MockWorkflowRunUseCaseMockRecorder) GetWorkflowsToRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowsToRun", reflect.TypeOf((*MockWorkflowRunUseCase)(nil).GetWorkflowsToRun))
}

// ListWorkflowRuns mocks base method.
func (m *MockWorkflowRunUseCase) ListWorkflowRuns() ([]domain.WorkflowRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkflowRuns")
	ret0, _ := ret[0].([]domain.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkflowRuns indicates an expected call of ListWorkflowRuns.
func (mr *MockWorkflowRunUseCaseMockRecorder) ListWorkflowRuns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkflowRuns", reflect.TypeOf((*MockWorkflowRunUseCase)(nil).ListWorkflowRuns))
}

// RunWorkflow mocks base method.
func (m *MockWorkflowRunUseCase) RunWorkflow(workflowID string, runnerSelector func(domain.Node) domain.NodeRunner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWorkflow", workflowID, runnerSelector)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWorkflow indicates an expected call of RunWorkflow.
func (mr *MockWorkflowRunUseCaseMockRecorder) RunWorkflow(workflowID, runnerSelector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWorkflow", reflect.TypeOf((*MockWorkflowRunUseCase)(nil).RunWorkflow), workflowID, runnerSelector)
}
