name: "hello-dependencies"
description: "A simple workflow example with dependencies"

trigger:
  type: "manual"

nodes:
  rs-sample:
    name: "rs-sample"

  node-sample:
    name: "nodejs-sample"
    dependencies:
      - rs-sample