name: hello-data
description: "A simple data example"

trigger:
  type: "interval"
  interval: 10

nodes:
  ask-name:
    name: "ask-name"
  answer-name:
    name: "answer-name"
    dependencies:
      - ask-name