// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_docker/client_mock.go -package=mock_docker
//

// Package mock_docker is a generated GoMock package.
package mock_docker

import (
	context "context"
	io "io"
	reflect "reflect"

	client "github.com/moby/moby/client"
	gomock "go.uber.org/mock/gomock"
)

// MockDockerClient is a mock of DockerClient interface.
type MockDockerClient struct {
	ctrl     *gomock.Controller
	recorder *MockDockerClientMockRecorder
	isgomock struct{}
}

// MockDockerClientMockRecorder is the mock recorder for MockDockerClient.
type MockDockerClientMockRecorder struct {
	mock *MockDockerClient
}

// NewMockDockerClient creates a new mock instance.
func NewMockDockerClient(ctrl *gomock.Controller) *MockDockerClient {
	mock := &MockDockerClient{ctrl: ctrl}
	mock.recorder = &MockDockerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerClient) EXPECT() *MockDockerClientMockRecorder {
	return m.recorder
}

// BuildImage mocks base method.
func (m *MockDockerClient) BuildImage(imageName, contextDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildImage", imageName, contextDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildImage indicates an expected call of BuildImage.
func (mr *MockDockerClientMockRecorder) BuildImage(imageName, contextDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildImage", reflect.TypeOf((*MockDockerClient)(nil).BuildImage), imageName, contextDir)
}

// RunContainer mocks base method.
func (m *MockDockerClient) RunContainer(image, dataDir, nodeName string, envVars map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunContainer", image, dataDir, nodeName, envVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunContainer indicates an expected call of RunContainer.
func (mr *MockDockerClientMockRecorder) RunContainer(image, dataDir, nodeName, envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunContainer", reflect.TypeOf((*MockDockerClient)(nil).RunContainer), image, dataDir, nodeName, envVars)
}

// MockmobyClient is a mock of mobyClient interface.
type MockmobyClient struct {
	ctrl     *gomock.Controller
	recorder *MockmobyClientMockRecorder
	isgomock struct{}
}

// MockmobyClientMockRecorder is the mock recorder for MockmobyClient.
type MockmobyClientMockRecorder struct {
	mock *MockmobyClient
}

// NewMockmobyClient creates a new mock instance.
func NewMockmobyClient(ctrl *gomock.Controller) *MockmobyClient {
	mock := &MockmobyClient{ctrl: ctrl}
	mock.recorder = &MockmobyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmobyClient) EXPECT() *MockmobyClientMockRecorder {
	return m.recorder
}

// ContainerCreate mocks base method.
func (m *MockmobyClient) ContainerCreate(ctx context.Context, options client.ContainerCreateOptions) (client.ContainerCreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCreate", ctx, options)
	ret0, _ := ret[0].(client.ContainerCreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerCreate indicates an expected call of ContainerCreate.
func (mr *MockmobyClientMockRecorder) ContainerCreate(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCreate", reflect.TypeOf((*MockmobyClient)(nil).ContainerCreate), ctx, options)
}

// ContainerLogs mocks base method.
func (m *MockmobyClient) ContainerLogs(ctx context.Context, containerID string, options client.ContainerLogsOptions) (client.ContainerLogsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerLogs", ctx, containerID, options)
	ret0, _ := ret[0].(client.ContainerLogsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerLogs indicates an expected call of ContainerLogs.
func (mr *MockmobyClientMockRecorder) ContainerLogs(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerLogs", reflect.TypeOf((*MockmobyClient)(nil).ContainerLogs), ctx, containerID, options)
}

// ContainerRemove mocks base method.
func (m *MockmobyClient) ContainerRemove(ctx context.Context, containerID string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerRemove", ctx, containerID, options)
	ret0, _ := ret[0].(client.ContainerRemoveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerRemove indicates an expected call of ContainerRemove.
func (mr *MockmobyClientMockRecorder) ContainerRemove(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerRemove", reflect.TypeOf((*MockmobyClient)(nil).ContainerRemove), ctx, containerID, options)
}

// ContainerStart mocks base method.
func (m *MockmobyClient) ContainerStart(ctx context.Context, containerID string, options client.ContainerStartOptions) (client.ContainerStartResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerStart", ctx, containerID, options)
	ret0, _ := ret[0].(client.ContainerStartResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerStart indicates an expected call of ContainerStart.
func (mr *MockmobyClientMockRecorder) ContainerStart(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerStart", reflect.TypeOf((*MockmobyClient)(nil).ContainerStart), ctx, containerID, options)
}

// ContainerWait mocks base method.
func (m *MockmobyClient) ContainerWait(ctx context.Context, containerID string, options client.ContainerWaitOptions) client.ContainerWaitResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerWait", ctx, containerID, options)
	ret0, _ := ret[0].(client.ContainerWaitResult)
	return ret0
}

// ContainerWait indicates an expected call of ContainerWait.
func (mr *MockmobyClientMockRecorder) ContainerWait(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerWait", reflect.TypeOf((*MockmobyClient)(nil).ContainerWait), ctx, containerID, options)
}

// ImageBuild mocks base method.
func (m *MockmobyClient) ImageBuild(ctx context.Context, buildContext io.Reader, options client.ImageBuildOptions) (client.ImageBuildResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageBuild", ctx, buildContext, options)
	ret0, _ := ret[0].(client.ImageBuildResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageBuild indicates an expected call of ImageBuild.
func (mr *MockmobyClientMockRecorder) ImageBuild(ctx, buildContext, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageBuild", reflect.TypeOf((*MockmobyClient)(nil).ImageBuild), ctx, buildContext, options)
}
